### ISSUE TITLE
import failed (macOS 10.13)

### ISSUE THREAD

**Issue by belm0** [tonybaloney/Pyjion#272]
macOS 10.13.6
pip 21.1.1

```
$ python
Python 3.9.0 (default, Jan 16 2021, 11:44:45)
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyjion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/john/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyjion/__init__.py", line 70, in <module>
    from ._pyjion import *  # NOQA
ModuleNotFoundError: No module named 'pyjion._pyjion'
```

install log
```
$ pip install pyjion --no-cache-dir
Collecting pyjion
  Downloading pyjion-0.15.0.tar.gz (136 kB)
     |████████████████████████████████| 136 kB 5.7 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: pyjion
  Building wheel for pyjion (PEP 517) ... done
  Created wheel for pyjion: filename=pyjion-0.15.0-py3-none-any.whl size=18401 sha256=3c3096b89c7b777ee86f3e03c33eaf8248e8578997425be94d7c445ea95de4e5
  Stored in directory: /private/var/folders/ww/51xbs7nx6t16x7mh225q9x1h0000gn/T/pip-ephem-wheel-cache-6avchvny/wheels/20/77/d9/d859ed84f8633d0c51271d83f04ccdcbbb0f70824faca69432
Successfully built pyjion
Installing collected packages: pyjion
Successfully installed pyjion-0.15.0
```

**Comment by ambv** [comment]
The wheels for macOS require Big Sur.

**Comment by belm0** [comment]
got it-- I see this in the changelog:

> Installable bdist_wheel for Ubuntu, Debian, macOS 10.15, 11 (10.16) and Windows x64

**Comment by belm0** [comment]
perhaps worth noting in the README, and maybe I'd move this text to the "Installing" section:

> To get started, you need to have .NET 5 installed, with Python 3.9 and the Pyjion package (I also recommend using a virtual environment).

**Comment by tonybaloney** [comment]
The error is now more useful
