### ISSUE TITLE
Spectral norm game benchmark will not run.

### ISSUE THREAD

**Issue by nlhnt** [tonybaloney/Pyjion#301]
Hello,  
leaving this as a notice.  
The following code will not with pyjion, the n-body problem runs without issues.  
I don't want to report every single stack trace, because the errors seem to be switching out. It is always something else that is not defined with each run.  
https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/spectralnorm-python3-8.html  
e.g. stack trace:  
```
Traceback (most recent call last):
  File "C:\my_playground\benchmark_game\spectral_norm\spectral_norm_pyjion.py", line 18, in <module>
    from multiprocessing import Pool
  File "C:\Users\***\.conda\envs\pyjion\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "C:\Users\***\.conda\envs\pyjion\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "C:\Users\***\.conda\envs\pyjion\lib\multiprocessing\reduction.py", line 15, in <module>
    import pickle
  File "C:\Users\***\.conda\envs\pyjion\lib\pickle.py", line 1136, in <module>
    class _Unpickler:
  File "C:\Users\***\.conda\envs\pyjion\lib\pickle.py", line 1744, in _Unpickler
    dispatch[STOP[0]] = load_stop
NameError: name 'load_long4' is not defined
```

**Comment by tonybaloney** [comment]
thanks for the report. this is an ongoing issue that needs to be fixed. I'll tackle it once I merge the generators PR

**Comment by tonybaloney** [comment]
I've put a spectral norm benchmark in the benchmarks folder. It looks like there was a bug on Pickle, which I'm struggling to reproduce. Can you share spectral_norm_pyjion.py
