### ISSUE TITLE
TypeError: Operation not supported on left-hand or right-hand operand.

### ISSUE THREAD

**Issue by oroppas** [tonybaloney/Pyjion#310]
When I tried to plot figure by matplotlib, `pyjion`  hit the wall:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 806, in callit
    func(*args)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\_backend_tk.py", line 239, in idle_draw
    self.draw()
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 9, in draw
    super().draw()
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\backend_agg.py", line 406, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\figure.py", line 2737, in draw
    mimage._draw_list_compositing_images(
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\_api\deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\axes\_base.py", line 2925, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\axis.py", line 1130, in draw
    ticks_to_draw = self._update_ticks()
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\axis.py", line 1017, in _update_ticks
    major_locs = self.get_majorticklocs()
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\axis.py", line 1249, in get_majorticklocs
    return self.major.locator()
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\ticker.py", line 2264, in __call__
    return self.tick_values(vmin, vmax)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\ticker.py", line 2272, in tick_values
    locs = self._raw_ticks(vmin, vmax)
  File "C:\Users\ryuta\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\ticker.py", line 2257, in _raw_ticks
    nticks = ((ticks <= _vmax) & (ticks >= _vmin)).sum()
TypeError: Operation not supported on left-hand or right-hand operand.
```

**Comment by tonybaloney** [comment]
Is there any way you could find out what types `ticks`, `_vmax` and `_vmin` are?

**Comment by oroppas** [comment]
Sure. Let me interrogate.

**Comment by oroppas** [comment]
```
type(ticks): <class 'numpy.ndarray'>
type(_vmax): <class 'float'>
type(_vmin): <class 'float'>
```

```
ticks: [250. 300. 350. 400. 450. 500. 550. 600. 650. 700.]
_vmax: 665.7883591867209
_vmin: 254.46341146729904
```

```
(ticks <= _vmax): [ True  True  True  True  True  True  True  True  True False]
(ticks >= _vmin): [False  True  True  True  True  True  True  True  True  True]
(ticks <= _vmax) & (ticks >= _vmin): [False  True  True  True  True  True  True  True  True False]
((ticks <= _vmax) & (ticks >= _vmin)).sum(): 8
```

**Comment by tonybaloney** [comment]
curious. That error message comes from
https://github.com/tonybaloney/Pyjion/blob/master/src/pyjion/binarycomp.cpp#L266

I haven't tried binary operators on many custom types yet. the error is coming from ndarray, its raising a NotImplemented from it's and operator. But this must be Pyjion's fault because that code would work before.

I'll try and reproduce on a smaller scale. ndarray support is important

**Comment by tonybaloney** [comment]
this reproduces the same thing:

```python
import pyjion
import unittest
import gc

class NumpyTestCase(unittest.TestCase):

    def setUp(self) -> None:
        pyjion.enable()

    def tearDown(self) -> None:
        pyjion.disable()
        gc.collect()

    def test_array_math(self):
        import numpy as np
        t = np.array([250., 300., 350., 400., 450., 500., 550., 600., 650., 700.])
        v = 44.2
        x = 55.3
        i = t <= 44.2
        print(i)
        j = (t <= v) & (t >= x)
        print(j)
```

**Comment by tonybaloney** [comment]
After some debugging, I found that numpy has custom logic for throwing NotImplemented errors and "tricking" CPython 
https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/core/src/common/binop_override.h#L10-L94

**Comment by oroppas** [comment]
Cool. I can plot by matplotlib with pyjion enabled.
I think it's really important for any python implementation
to be able to work "as is", without requiring any modification to the existing code.

Thank you for your hard work!

**Comment by tonybaloney** [comment]
> Cool. I can plot by matplotlib with pyjion enabled.
> I think it's really important for any python implementation
> to be able to work "as is", without requiring any modification to the existing code.
> 
> Thank you for your hard work!

100%. this should have worked beforehand. It never crossed my mind that the `x <= y` operation would return anything other than a boolean!
