### ISSUE TITLE
OverflowError enabling pyjion in ipython

### ISSUE THREAD

**Issue by pfw** [tonybaloney/Pyjion#400]
This is on Apple M1 using the latest rc.

```
❯ ipython            
Python 3.10.0 (v3.10.0:b494f5935c, Oct  4 2021, 14:59:19) [Clang 12.0.5 (clang-1205.0.22.11)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.28.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pyjion

In [2]: pyjion.enable()
Out[2]: True

Traceback (most recent call last):
  File "/experiments/pyjion/env/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/experiments/pyjion/env/lib/python3.10/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 563, in mainloop
    self.interact()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 546, in interact
    code = self.prompt_for_code()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 472, in prompt_for_code
    text = self.pt_app.prompt(
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1020, in prompt
    return self.app.run(
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 891, in run
    return loop.run_until_complete(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 816, in run_async
    return await _run_async2()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 792, in _run_async2
    result = await _run_async()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 728, in _run_async
    self._redraw()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 552, in _redraw
    self.context.copy().run(run_in_context)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 535, in run_in_context
    self.renderer.render(self, self.layout)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/renderer.py", line 638, in render
    layout.container.preferred_height(size.columns, size.rows).preferred,
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/layout/containers.py", line 325, in preferred_height
    dimensions = [
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/layout/containers.py", line 326, in <listcomp>
    c.preferred_height(width, max_available_height) for c in self._all_children
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/layout/containers.py", line 795, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/layout/containers.py", line 328, in preferred_height
    return sum_layout_dimensions(dimensions)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/layout/dimension.py", line 125, in sum_layout_dimensions
    return Dimension(min=min, max=max, preferred=preferred)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/layout/dimension.py", line 50, in __init__
    assert max is None or max >= 0
OverflowError: Pyjion failed to unbox the integer 1000000000000000000000000000000 because it is too large.

```

**Comment by adamchainz** [comment]
THe "failed to unbox the integer" message is also triggered by importing `ipaddress` from the standard library:

```
$ python -c 'import pyjion; pyjion.enable(); import ipaddress'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/.../lib/python3.10/ipaddress.py", line 2257, in <module>
    class _IPv6Constants:
  File "/.../lib/python3.10/ipaddress.py", line 2259, in _IPv6Constants
    _linklocal_network = IPv6Network('fe80::/10')
  File "/.../lib/python3.10/ipaddress.py", line 2216, in __init__
    packed = int(self.network_address)
OverflowError: Pyjion failed to unbox the integer 338288524927261089654018896841347694592 because it is too large.
```

I discovered this trying to run Django's test suite with pyjion 👀

(Python 3.10, pyjion 1.0.0rc4, x86 mac)

**Comment by tonybaloney** [comment]
I'm working on a permanent solution in the next release. Pyjion is optimising int's into 64 bit stack values, if the value at runtime wasn't too large, but there are times when the function is run a second time and suddenly the value exceeds the limits for a 64-bit int, so this exception is thrown. I'm working on an overflow field so that the program can continue executing

**Comment by tonybaloney** [comment]
"I discovered this trying to run Django's test suite with pyjion 👀" @adamchainz 👂

**Comment by tonybaloney** [comment]
> THe "failed to unbox the integer" message is also triggered by importing `ipaddress` from the standard library:
> 
> ```
> $ python -c 'import pyjion; pyjion.enable(); import ipaddress'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/.../lib/python3.10/ipaddress.py", line 2257, in <module>
>     class _IPv6Constants:
>   File "/.../lib/python3.10/ipaddress.py", line 2259, in _IPv6Constants
>     _linklocal_network = IPv6Network('fe80::/10')
>   File "/.../lib/python3.10/ipaddress.py", line 2216, in __init__
>     packed = int(self.network_address)
> OverflowError: Pyjion failed to unbox the integer 338288524927261089654018896841347694592 because it is too large.
> ```
> 
> I discovered this trying to run Django's test suite with pyjion 👀
> 
> (Python 3.10, pyjion 1.0.0rc4, x86 mac)

its the same error, but this is a separate, easily fixable bug. Have created an issue #404

**Comment by adamchainz** [comment]
> "I discovered this trying to run Django's test suite with pyjion 👀" @adamchainz 👂 

I thought it would be a good varied test suite with a real world use case. If I see it working I'll blog about it ;)
