### ISSUE TITLE
Exception Pyjion PGC expected int, but (4, 8) is a tuple.

### ISSUE THREAD

**Issue by pfw** [tonybaloney/Pyjion#407]
Hi Anthony... I just saw you fixed the bigint wrapping so had another go and ran into another ipython induced bug I'm afraid.

After the ```pyjion.enable()``` wait a second or so and it gets into loop like below - the first error has ```Exception Pyjion PGC expected int, but (4, 8) is a tuple.``` the it continues indefinitely with ```Exception Pyjion PGC expected int, but () is a tuple.```.

While this is happening it doesn't response to CTRL-C and uses 5-8% CPU. Let me know if you need anything else. ACT schools/daycare being back would be good but it does give me some time to play with interesting things while keeping an eye on kids. ;-)

```
❯ ipython
Python 3.10.0 (v3.10.0:b494f5935c, Oct  4 2021, 14:59:19) [Clang 12.0.5 (clang-1205.0.22.11)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.28.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pyjion

In [2]: pyjion.enable()
Out[2]: True


Unhandled exception in event loop:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/input/vt100.py", line 168, in callback_wrapper
    callback()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 691, in read_from_input
    self.key_processor.process_keys()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_processor.py", line 274, in process_keys
    self._process_coroutine.send(key_press)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_processor.py", line 169, in _process
    matches = self._get_matches(buffer)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_processor.py", line 127, in _get_matches
    return [b for b in self._bindings.get_bindings_for_keys(keys) if b.filter()]
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 1309, in get_bindings_for_keys
    return self._key_bindings.get_bindings_for_keys(keys)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 489, in get_bindings_for_keys
    self._update_cache()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 568, in _update_cache
    expected_version = tuple(r._version for r in self.registries)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 568, in <genexpr>
    expected_version = tuple(r._version for r in self.registries)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 485, in _version
    self._update_cache()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 526, in _update_cache
    expected_version = self.key_bindings._version
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 485, in _version
    self._update_cache()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 526, in _update_cache
    expected_version = self.key_bindings._version

Exception Pyjion PGC expected int, but (4, 8) is a tuple.

Unhandled exception in event loop:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/input/vt100.py", line 168, in callback_wrapper
    callback()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 691, in read_from_input
    self.key_processor.process_keys()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_processor.py", line 274, in process_keys
    self._process_coroutine.send(key_press)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_processor.py", line 169, in _process
    matches = self._get_matches(buffer)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_processor.py", line 127, in _get_matches
    return [b for b in self._bindings.get_bindings_for_keys(keys) if b.filter()]
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 1309, in get_bindings_for_keys
    return self._key_bindings.get_bindings_for_keys(keys)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 489, in get_bindings_for_keys
    self._update_cache()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 568, in _update_cache
    expected_version = tuple(r._version for r in self.registries)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 568, in <genexpr>
    expected_version = tuple(r._version for r in self.registries)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 485, in _version
    self._update_cache()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 568, in _update_cache
    expected_version = tuple(r._version for r in self.registries)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 568, in <genexpr>
    expected_version = tuple(r._version for r in self.registries)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 485, in _version
    self._update_cache()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 526, in _update_cache
    expected_version = self.key_bindings._version
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 485, in _version
    self._update_cache()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 568, in _update_cache
    expected_version = tuple(r._version for r in self.registries)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 568, in <genexpr>
    expected_version = tuple(r._version for r in self.registries)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 485, in _version
    self._update_cache()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 528, in _update_cache
    if self._last_version != expected_version:

Exception Pyjion PGC expected int, but () is a tuple.

```

**Comment by pfw** [comment]
Another twist on this kind of error...

If using bpython then depending on the order of importing pyjion there is different behaviour.

When call enable() without importing, then correcting that and trying again I get another PGC error but if I just do the correct import sequence then the error just looks like an internal bpython error.

```
❯ bpython
bpython version 0.21 on top of Python 3.10.0 /experiments/pyjion/env/bin/python3
>>> pyjion.enable()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    pyjion.enable()
NameError: name 'pyjion' is not defined
>>> import pyjion
>>> pyjion.enable()
True

Traceback (most recent call last):
  File "/experiments/pyjion/env/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/experiments/pyjion/env/lib/python3.10/site-packages/bpython/curtsies.py", line 201, in main
    exit_value = repl.mainloop(True, paste)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/bpython/curtsies.py", line 121, in mainloop
    self.process_event_and_paint(e)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/bpython/curtsies.py", line 85, in process_event_and_paint
    self.process_event(e)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/bpython/curtsiesfrontend/repl.py", line 611, in process_event
    return self.process_control_event(e)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/bpython/curtsiesfrontend/repl.py", line 629, in process_control_event
    self.run_code_and_maybe_finish()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/bpython/curtsiesfrontend/repl.py", line 1168, in run_code_and_maybe_finish
    r = self.coderunner.run_code(for_code=for_code)
pyjion.PyjionUnboxingError: Pyjion PGC expected bool, but <bpython.curtsiesfrontend.coderunner.Done object at 0x103f754e0> is a Done.
```

and with the correct import and enable sequence.


```
❯ bpython
bpython version 0.21 on top of Python 3.10.0 /experiments/pyjion/env/bin/python3
>>> import pyjion
>>> pyjion.enable()
Traceback (most recent call last):
  File "/experiments/pyjion/env/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/experiments/pyjion/env/lib/python3.10/site-packages/bpython/curtsies.py", line 201, in main
    exit_value = repl.mainloop(True, paste)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/bpython/curtsies.py", line 121, in mainloop
    self.process_event_and_paint(e)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/bpython/curtsies.py", line 95, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/experiments/pyjion/env/lib/python3.10/site-packages/bpython/curtsiesfrontend/repl.py", line 1568, in paint
    lines = paint.display_linize(self.current_cursor_line + "X", width)
  File "/experiments/pyjion/env/lib/python3.10/site-packages/bpython/curtsiesfrontend/repl.py", line 1374, in current_cursor_line
    return self.current_cursor_line_without_suggestion + suggest(
TypeError: can only concatenate str (not "FmtStr") to str

```

**Comment by tonybaloney** [comment]
You can get around this by doing `pyjion.config(pgc=False)` before doing `pyjion.enable()`, it'll disable all the runtime profiling that emits these errors. 
Although that typeerror doesn't look related

**Comment by pfw** [comment]
Agreed the TypeError doesn’t look related but it’s odd the only difference is the order of commands with no import first. I’ll check out the TypeError separately to see if that is completely unrelated.

**Comment by pfw** [comment]
I've had a look and the TypeError is falling out of the shutdown process when handling system errors, so just a side effect. There is definitely something odd about the behaviour when calling before importing - I wonder if the error is the same but the stacktrace is purely a timing issue.

As an aside - are bug reports like these ones a bit like a whack-a-mole and just hitting areas that you are expecting to not be fully covered yet or are they still worthwhile at this stage?

**Comment by pfw** [comment]
This no longer blows up on 1.2.0
