### ISSUE TITLE
Django unboxing error with PGC, segfault without PGC

### ISSUE THREAD

**Issue by adamchainz** [tonybaloney/Pyjion#424]
Trying to run Django's test suite on its latest commit 91acfc3514280370535f1dd6bebee57760bac7b9 with Pyjion 1.0.0, with `runtests.py` patched to enable pyjion at the top.

First attempt:

```
$ ./runtests.py admin_changelist
Testing against Django installed in '/.../django/django'
Traceback (most recent call last):
  File "/.../3.10.0/lib/python3.10/logging/config.py", line 544, in configure
    formatters[name] = self.configure_formatter(
  File "/.../3.10.0/lib/python3.10/logging/config.py", line 656, in configure_formatter
    result = self.configure_custom(config)
  File "/.../3.10.0/lib/python3.10/logging/config.py", line 469, in configure_custom
    c = config.pop('()')
  File "/.../3.10.0/lib/python3.10/logging/config.py", line 334, in pop
    value = dict.pop(self, key, default)
pyjion.PyjionUnboxingError: Pyjion PGC expected bool, but 'django.utils.log.ServerFormatter' is a str. Try disabling PGC pyjion.config(pgc=False) to avoid hitting this error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.../django/tests/./runtests.py", line 661, in <module>
    failures = django_tests(
  File "/.../django/tests/./runtests.py", line 352, in django_tests
    test_labels, state = setup_run_tests(verbosity, start_at, start_after, test_labels)
  File "/.../django/tests/./runtests.py", line 282, in setup_run_tests
    test_modules, state = setup_collect_tests(start_at, start_after, test_labels=test_labels)
  File "/.../django/tests/./runtests.py", line 244, in setup_collect_tests
    django.setup()
  File "/.../django/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/.../django/django/utils/log.py", line 72, in configure_logging
    logging.config.dictConfig(DEFAULT_LOGGING)
  File "/.../3.10.0/lib/python3.10/logging/config.py", line 810, in dictConfig
    dictConfigClass(config).configure()
  File "/.../3.10.0/lib/python3.10/logging/config.py", line 547, in configure
    raise ValueError('Unable to configure '
ValueError: Unable to configure formatter 'django.server'
```

After adding `pyjion.config(pgc=False)` as per the message:

```
$ USE_PYJION=1 ./runtests.py admin_changelist
Testing against Django installed in '/.../django/django'
Found 70 test(s).
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "/.../django/tests/./runtests.py", line 662, in <module>
    failures = django_tests(
  File "/.../django/tests/./runtests.py", line 382, in django_tests
    failures = test_runner.run_tests(test_labels)
  File "/.../django/django/test/runner.py", line 927, in run_tests
    old_config = self.setup_databases(
  File "/.../django/django/test/runner.py", line 830, in setup_databases
    return _setup_databases(
  File "/.../django/django/test/utils.py", line 208, in setup_databases
    connection.creation.create_test_db(
  File "/.../django/django/db/backends/base/creation.py", line 74, in create_test_db
    call_command(
  File "/.../django/django/core/management/__init__.py", line 187, in call_command
    return command.execute(*args, **defaults)
  File "/.../django/django/core/management/base.py", line 407, in execute
    output = self.handle(*args, **options)
  File "/.../django/django/core/management/base.py", line 88, in wrapped
    res = handle_func(*args, **kwargs)
  File "/.../django/django/core/management/commands/migrate.py", line 277, in handle
    emit_post_migrate_signal(
  File "/.../django/django/core/management/sql.py", line 46, in emit_post_migrate_signal
    models.signals.post_migrate.send(
  File "/.../django/django/dispatch/dispatcher.py", line 170, in send
    return [
  File "/.../django/django/dispatch/dispatcher.py", line 171, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/.../django/django/contrib/auth/management/__init__.py", line 72, in create_permissions
    all_perms = set(Permission.objects.using(using).filter(
  File "/.../django/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/.../django/django/db/models/query.py", line 1358, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/.../django/django/db/models/query.py", line 140, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/.../django/django/db/models/sql/compiler.py", line 1159, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/.../django/django/db/models/sql/compiler.py", line 1191, in execute_sql
    sql, params = self.as_sql()
  File "/.../django/django/db/models/sql/compiler.py", line 531, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/.../django/django/db/models/sql/compiler.py", line 60, in pre_sql_setup
    order_by = self.get_order_by()
  File "/.../django/django/db/models/sql/compiler.py", line 390, in get_order_by
    resolved = expr.resolve_expression(self.query, allow_joins=True, reuse=None)
  File "/.../django/django/db/models/expressions.py", line 248, in resolve_expression
    c.set_source_expressions([
  File "/.../django/django/db/models/expressions.py", line 182, in set_source_expressions
    assert not exprs
AssertionError
Fatal Python error: Segmentation fault

Current thread 0x0000000110e32e00 (most recent call first):
  Garbage-collecting
  <no Python frame>

Extension modules: pyjion._pyjion, pywatchman.bser, markupsafe._speedups, _scproxy (total: 4)
[1]    47147 segmentation fault  USE_PYJION=1 ./runtests.py admin_changelist
```

segfault sadface :(

Potentially an interesting broken function, it does nothing but assert:

```
def set_source_expressions(self, exprs):
    assert not exprs
```

**Comment by tonybaloney** [comment]
The issue starts here somewhere, running debug mode I can see a negative reference count, which likely causes the segfault afterward. 

```
Testing against Django installed in '/Users/anthonyshaw/projects/django/django'
Found 70 test(s).
Creating test database for alias 'default'...
/Users/anthonyshaw/CLionProjects/pyjion/src/pyjion/intrins.cpp:2048: _Py_NegativeRefcount: Assertion failed: object has negative ref count
Enable tracemalloc to get the memory block allocation traceback

object address  : 0x10afe5360
object refcount : -1
object type     : 0x107eb7440
object type name: list
object repr     : <refcnt -1 at 0x10afe5360>

Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: initialized

Current thread 0x0000000110e59600 (most recent call first):
  File "/Users/anthonyshaw/projects/django/django/db/migrations/state.py", line 762 in flatten_bases
  File "/Users/anthonyshaw/projects/django/django/db/migrations/state.py", line 772 in from_model
  File "/Users/anthonyshaw/projects/django/django/db/migrations/state.py", line 550 in __init__
  File "/Users/anthonyshaw/projects/django/django/db/migrations/state.py", line 505 in apps
  File "/Users/anthonyshaw/projects/django/django/utils/functional.py", line 48 in __get__
  File "/Users/anthonyshaw/projects/django/django/core/management/commands/migrate.py", line 211 in handle
  File "/Users/anthonyshaw/projects/django/django/core/management/base.py", line 88 in wrapped
  File "/Users/anthonyshaw/projects/django/django/core/management/base.py", line 407 in execute
  File "/Users/anthonyshaw/projects/django/django/core/management/__init__.py", line 187 in call_command
  File "/Users/anthonyshaw/projects/django/django/db/backends/base/creation.py", line 74 in create_test_db
  File "/Users/anthonyshaw/projects/django/django/test/utils.py", line 208 in setup_databases
  File "/Users/anthonyshaw/projects/django/django/test/runner.py", line 830 in setup_databases
  File "/Users/anthonyshaw/projects/django/django/test/runner.py", line 927 in run_tests
  File "/Users/anthonyshaw/projects/django/tests/runtests.py", line 377 in django_tests
  File "/Users/anthonyshaw/projects/django/tests/runtests.py", line 660 in <module>

Extension modules: markupsafe._speedups, _scproxy, pyjion._pyjion (total: 3)
Signal: SIGABRT (signal SIGABRT)
Signal: SIGABRT (signal SIGABRT)
Terminated due to signal 6

Process finished with exit code 6
```

**Comment by adamchainz** [comment]
I added `debug=True` to `pyjion.config()` and used `-X dev`, and I only see the same as my second traceback. Is there some other debug mode I should be activating? Or should I try with the latest `main` branch of pyjion?

**Comment by tonybaloney** [comment]
Found it!! 🥳 

A recursive function where the argument is a gc-collection, like a list, appears in the Django source code. 
Doesn't look like I'd written a test for this before and it causes a bug which would start segfaults.

The list ends up being deallocated during the recursive call because something is decrefing the ref count too many times. Just need to figure out which opcode/behaviour!

```python
def test_recursive_container():
    def f():
        def flatten(word):
            k = []
            for item in word:
                if isinstance(item, tuple):
                    k.extend(flatten(item))
                else:
                    k.append(item)
            return k
        return flatten(((1245, 4324), 31235, ((123454,), 31234)))

    assert f() == [1245, 4324, 31235, 123454, 31234]
```

**Comment by adamchainz** [comment]
👏👏👏 That's tricky!

**Comment by tonybaloney** [comment]
That was actually a separate bug (which I've just fixed)

```
/Users/anthonyshaw/projects/cpython-3.10/python.exe /Users/anthonyshaw/projects/django/tests/runtests.py admin_changelist
Testing against Django installed in '/Users/anthonyshaw/projects/django/django'
Compiling failed <lambda> from <string> line 1

Found 70 test(s).
Creating test database for alias 'default'...
Compiling failed <lambda> from <string> line 1

Compiling failed <lambda> from <string> line 1

Compiling failed <lambda> from <string> line 1

Compiling failed <lambda> from <string> line 1

Traceback (most recent call last):
  File "/Users/anthonyshaw/projects/django/tests/runtests.py", line 660, in <module>
    failures = django_tests(
  File "/Users/anthonyshaw/projects/django/tests/runtests.py", line 377, in django_tests
    failures = test_runner.run_tests(test_labels)
  File "/Users/anthonyshaw/projects/django/django/test/runner.py", line 927, in run_tests
    old_config = self.setup_databases(
  File "/Users/anthonyshaw/projects/django/django/test/runner.py", line 830, in setup_databases
    return _setup_databases(
  File "/Users/anthonyshaw/projects/django/django/test/utils.py", line 208, in setup_databases
    connection.creation.create_test_db(
  File "/Users/anthonyshaw/projects/django/django/db/backends/base/creation.py", line 74, in create_test_db
    call_command(
  File "/Users/anthonyshaw/projects/django/django/core/management/__init__.py", line 187, in call_command
    return command.execute(*args, **defaults)
  File "/Users/anthonyshaw/projects/django/django/core/management/base.py", line 407, in execute
    output = self.handle(*args, **options)
  File "/Users/anthonyshaw/projects/django/django/core/management/base.py", line 88, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/anthonyshaw/projects/django/django/core/management/commands/migrate.py", line 277, in handle
    emit_post_migrate_signal(
  File "/Users/anthonyshaw/projects/django/django/core/management/sql.py", line 46, in emit_post_migrate_signal
    models.signals.post_migrate.send(
  File "/Users/anthonyshaw/projects/django/django/dispatch/dispatcher.py", line 170, in send
    return [
  File "/Users/anthonyshaw/projects/django/django/dispatch/dispatcher.py", line 171, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/anthonyshaw/projects/django/django/contrib/auth/management/__init__.py", line 72, in create_permissions
    all_perms = set(Permission.objects.using(using).filter(
  File "/Users/anthonyshaw/projects/django/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/Users/anthonyshaw/projects/django/django/db/models/query.py", line 1358, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/anthonyshaw/projects/django/django/db/models/query.py", line 140, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/anthonyshaw/projects/django/django/db/models/sql/compiler.py", line 1159, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/Users/anthonyshaw/projects/django/django/db/models/sql/compiler.py", line 1191, in execute_sql
    sql, params = self.as_sql()
  File "/Users/anthonyshaw/projects/django/django/db/models/sql/compiler.py", line 531, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/Users/anthonyshaw/projects/django/django/db/models/sql/compiler.py", line 60, in pre_sql_setup
    order_by = self.get_order_by()
  File "/Users/anthonyshaw/projects/django/django/db/models/sql/compiler.py", line 390, in get_order_by
    resolved = expr.resolve_expression(self.query, allow_joins=True, reuse=None)
  File "/Users/anthonyshaw/projects/django/django/db/models/expressions.py", line 248, in resolve_expression
    c.set_source_expressions([
  File "/Users/anthonyshaw/projects/django/django/db/models/expressions.py", line 182, in set_source_expressions
    assert not exprs
AssertionError
Modules/gcmodule.c:454: visit_decref: Assertion "!_PyObject_IsFreed(op)" failed
Enable tracemalloc to get the memory block allocation traceback

object address  : 0x10a4b80b0
object refcount : 1
object type     : 0x109692460
object type name: dict
object repr     : Exception: EXC_BAD_ACCESS (code=1, address=0x58)
```

This seems to just coincidentally be the line where the GC runs. One of the dictionaries in the GC has an invalid reference count for one of its members (FWIW, this is a theme and the cause of 90% of the bugs)

**Comment by tonybaloney** [comment]
@adamchainz #447 fixes this, I can run the whole Django test suite. Will ship in 1.1.1

**Comment by tonybaloney** [comment]
@adamchainz please update to 1.1.1 and raise issues for any failing tests that shouldn't be there.

I initially ran the suites under level 0 (`pyjion.config(level=0, pgc=False)`), once that passes, you can try level 1 and 2 if you're feeling dangerous

**Comment by adamchainz** [comment]
Upgraded, got the tests passing.

I always feel dangerous.
