### ISSUE TITLE
pyjion.config level 2 errors

### ISSUE THREAD

**Issue by guizhenwei** [tonybaloney/Pyjion#464]
Pyjion version: 1.2.1
Python:  3.10.1
OS: Windows 10 64bit

With the following code:

```
import pyjion
pyjion.enable()
pyjion.config(level=1)
```

All good without problems.

If i set `pyjion.config(level=2)` then error as below:

```
Traceback (most recent call last):
  File "c:\Users\guizh\.code\replayer_git\replayer.py", line 9, in <module>
    import configparser
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 522, in <module>
    class LegacyInterpolation(Interpolation):
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 526, in LegacyInterpolation
    _KEYCRE = re.compile(r"%\(([^)]*)\)s|.")
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\re.py", line 251, in compile
    return _compile(pattern, flags)
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 768, in compile
    code = _code(p, flags)
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 604, in _code
    _compile_info(code, p, flags)
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 552, in _compile_info
    prefix, prefix_skip, got_all = _get_literal_prefix(pattern, flags)
pyjion.PyjionUnboxingError: Optimizations are invalid. Pyjion PGC expected int, but None is a NoneType. Try disabling PGC pyjion.config(pgc=False) or lowering the optimization level to avoid hitting this error.
```

Then as the prompt if i set `pyjion.config(level=2, pgc=False)` :

```
import pyjion
pyjion.enable()
pyjion.config(level=2, pgc=False)
```

Error info:
```
Traceback (most recent call last):
  File "c:\Users\guizh\.code\replayer_git\replayer.py", line 23, in <module>
    from uuid import uuid4
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\uuid.py", line 725, in <module>
    NAMESPACE_DNS = UUID('6ba7b810-9dad-11d1-80b4-00c04fd430c8')
  File "C:\Users\guizh\AppData\Local\Programs\Python\Python310\lib\uuid.py", line 211, in __init__
    raise ValueError('int is out of range (need a 128-bit value)')
ValueError: int is out of range (need a 128-bit value)
```

Hope the above info will be useful.

**Comment by tonybaloney** [comment]
The guidance with the levels is to go for the highest level that works and passes your test suite. 2 makes some optimisations around integer arithmetic, but will fail if it compiles an optimized path for integers and then is provided a non-numeric value (e.g. None).

Recommend you stick with level 1 for now. 

I'm working on improving the specialisations so it could potentially branch to another path and allow slower calculation

**Comment by guizhenwei** [comment]
Thanks for the explanation.

Feel free to close this report as need.
