### ISSUE TITLE
ImportError using Pyjion 1.2.6

### ISSUE THREAD

**Issue by smitht06** [tonybaloney/Pyjion#477]
Hi,

I saw others had this error and it was reported to be fixed in 1.2.2 but i am still getting it. I have MACOS 12.2 running M1 Pro:

pyjion
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyjion/__init__.py", line 90, in <module>
    from ._pyjion import (
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyjion/_pyjion.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_getJit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pyjion", line 5, in <module>
    from pyjion.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyjion/__init__.py", line 106, in <module>
    raise ImportError(
ImportError:
Failed to import the compiled Pyjion module (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyjion/_pyjion.cpython-310-darwin.so). This normally means something went wrong during pip install
and the binaries weren't compiled. Make sure you update pip before installing to get the right wheel.
If that doesn't work, run pip in verbose mode, or file an issue at https://github.com/tonybaloney/pyjion/.

**Comment by tonybaloney** [comment]
Hi, this is actually a different issue. Which version of .net do you have installed?

**Comment by smitht06** [comment]
6.0.101

**Comment by eureka-0** [comment]
I had .net6 and python3.10.2 and I used `pip install pyjion`. Then I encountered the same problem. Have you solved it?

**Comment by gtmtg** [comment]
Same issue here - installing through poetry

**Comment by david-tao-as01** [comment]
Same issue here using pyjion 1.2.6 with python 3.10.4 and .net 6.0.103

**Comment by SichangHe** [comment]
Same issue  with pip 22.2.2.

**Comment by GoEdgar** [comment]
Have the same issue on Mac M1 with pyjion 2.0.0 and .NET 7
