### ISSUE TITLE
Apple Silicon build failures

### ISSUE THREAD

**Issue by pfw** [tonybaloney/Pyjion#80]
On first pass with Python 3.9.1 and .Net dotnet-sdk-5.0.101-osx-x64.pkg the build fails with

```
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: pyjion
  Running setup.py develop for pyjion
    ERROR: Command errored out with exit status 1:
     command: /Users/pfw/thirdfloor/experiments/pyjion/.env/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/setup.py'"'"'; __file__='"'"'/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/pfw/thirdfloor/experiments/pyjion/Pyjion/
    Complete output (70 lines):
    Not searching for unused variables given on the command line.
    -- The C compiler identification is AppleClang 12.0.0.12000032
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is AppleClang 12.0.0.12000032
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_cmake_test_compile/build
    CMake Error at CMakeLists.txt:2 (project):
      Running
    
       '/private/var/folders/qv/43hqbb712s7_vn18b0f88w340000gn/T/pip-build-env-rj9pw9cw/overlay/bin/ninja' '--version'
    
      failed with:
    
       No such file or directory
    
    
    -- Configuring incomplete, errors occurred!
    See also "/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_skbuild/macosx-11.0-arm64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
    See also "/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_skbuild/macosx-11.0-arm64-3.9/cmake-build/CMakeFiles/CMakeError.log".
      File "/private/var/folders/qv/43hqbb712s7_vn18b0f88w340000gn/T/pip-build-env-3o0qhja_/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 583, in setup
        env = cmkr.configure(cmake_args,
      File "/private/var/folders/qv/43hqbb712s7_vn18b0f88w340000gn/T/pip-build-env-3o0qhja_/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 229, in configure
        raise SKBuildError(
    An error occurred while configuring with CMake.
      Command:
        cmake /Users/pfw/thirdfloor/experiments/pyjion/Pyjion -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_skbuild/macosx-11.0-arm64-3.9/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/Users/pfw/thirdfloor/experiments/pyjion/.env/bin/python3.9 -DPYTHON_VERSION_STRING:STRING=3.9.1 -DPYTHON_INCLUDE_DIR:PATH=/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/Library/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/qv/43hqbb712s7_vn18b0f88w340000gn/T/pip-build-env-3o0qhja_/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=11.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64
      Source directory:
        /Users/pfw/thirdfloor/experiments/pyjion/Pyjion
      Working directory:
        /Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_skbuild/macosx-11.0-arm64-3.9/cmake-build
    Please see CMake's output for more information.
    
    
    --------------------------------------------------------------------------------
    -- Trying "Ninja" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja" generator - success
    --------------------------------------------------------------------------------
    
    Configuring Project
      Working directory:
        /Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_skbuild/macosx-11.0-arm64-3.9/cmake-build
      Command:
        cmake /Users/pfw/thirdfloor/experiments/pyjion/Pyjion -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_skbuild/macosx-11.0-arm64-3.9/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/Users/pfw/thirdfloor/experiments/pyjion/.env/bin/python3.9 -DPYTHON_VERSION_STRING:STRING=3.9.1 -DPYTHON_INCLUDE_DIR:PATH=/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/Library/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/qv/43hqbb712s7_vn18b0f88w340000gn/T/pip-build-env-3o0qhja_/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=11.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64
    
    Traceback (most recent call last):
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/pfw/thirdfloor/experiments/pyjion/.env/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/setup.py'"'"'; __file__='"'"'/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

```

When forcing x86 Python 3.9.1 it barfs with a different error:

```
(.env) ➜  pyjion python               
Python 3.9.1 (default, Dec  8 2020, 13:10:53) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.platform()
'macOS-11.0.1-x86_64-i386-64bit'
>>> ^D
(.env) ➜  pyjion dotnet --info        
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
(.env) ➜  pyjion pip install -e Pyjion
Obtaining file:///Users/pfw/thirdfloor/experiments/pyjion/Pyjion
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: pyjion
  Running setup.py develop for pyjion
    ERROR: Command errored out with exit status 1:
     command: /Users/pfw/thirdfloor/experiments/pyjion/.env/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/setup.py'"'"'; __file__='"'"'/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/pfw/thirdfloor/experiments/pyjion/Pyjion/
    Complete output (70 lines):
    Not searching for unused variables given on the command line.
    -- The C compiler identification is AppleClang 12.0.0.12000032
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is AppleClang 12.0.0.12000032
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_cmake_test_compile/build
    CMake Error at CMakeLists.txt:2 (project):
      Running
    
       '/private/var/folders/qv/43hqbb712s7_vn18b0f88w340000gn/T/pip-build-env-5vxudo7q/overlay/bin/ninja' '--version'
    
      failed with:
    
       No such file or directory
    
    
    -- Configuring incomplete, errors occurred!
    See also "/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_skbuild/macosx-11.0-x86_64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
    See also "/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_skbuild/macosx-11.0-x86_64-3.9/cmake-build/CMakeFiles/CMakeError.log".
      File "/private/var/folders/qv/43hqbb712s7_vn18b0f88w340000gn/T/pip-build-env-95wkx41d/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 583, in setup
        env = cmkr.configure(cmake_args,
      File "/private/var/folders/qv/43hqbb712s7_vn18b0f88w340000gn/T/pip-build-env-95wkx41d/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 229, in configure
        raise SKBuildError(
    An error occurred while configuring with CMake.
      Command:
        cmake /Users/pfw/thirdfloor/experiments/pyjion/Pyjion -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_skbuild/macosx-11.0-x86_64-3.9/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/Users/pfw/thirdfloor/experiments/pyjion/.env/bin/python3.9 -DPYTHON_VERSION_STRING:STRING=3.9.1 -DPYTHON_INCLUDE_DIR:PATH=/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/qv/43hqbb712s7_vn18b0f88w340000gn/T/pip-build-env-95wkx41d/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=11.0 -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64
      Source directory:
        /Users/pfw/thirdfloor/experiments/pyjion/Pyjion
      Working directory:
        /Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_skbuild/macosx-11.0-x86_64-3.9/cmake-build
    Please see CMake's output for more information.
    
    
    --------------------------------------------------------------------------------
    -- Trying "Ninja" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja" generator - success
    --------------------------------------------------------------------------------
    
    Configuring Project
      Working directory:
        /Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_skbuild/macosx-11.0-x86_64-3.9/cmake-build
      Command:
        cmake /Users/pfw/thirdfloor/experiments/pyjion/Pyjion -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/_skbuild/macosx-11.0-x86_64-3.9/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/Users/pfw/thirdfloor/experiments/pyjion/.env/bin/python3.9 -DPYTHON_VERSION_STRING:STRING=3.9.1 -DPYTHON_INCLUDE_DIR:PATH=/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/qv/43hqbb712s7_vn18b0f88w340000gn/T/pip-build-env-95wkx41d/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=11.0 -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64
    
    Traceback (most recent call last):
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/pfw/thirdfloor/experiments/pyjion/.env/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/setup.py'"'"'; __file__='"'"'/Users/pfw/thirdfloor/experiments/pyjion/Pyjion/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

Let me know if there is anything else to poke at that might help. From my reading it looks like .Net 6 Preview in late Jan is required for arm64 support at lease on that.

**Comment by tonybaloney** [comment]
Thanks! This is really helpful to see a full trace

**Comment by tonybaloney** [comment]
this is now resolved and will be released in 1.0.0rc4

**Comment by tonybaloney** [comment]
You'll need the native ARM64 installation of .NET 6 to get it working

**Comment by pfw** [comment]
Good one. Anything that specially needs testing with this? I've got a reasonable size Flask app with a number of different DB backends that I can relatively easily test against new python builds. Is it at the stage that getting performance numbers is helpful?
